# Generated by Django 2.2 on 2019-04-26 03:23

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test activity', max_length=100, verbose_name='活动名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('activity_type', models.CharField(choices=[('S', 'study'), ('O', 'online_study'), ('A', 'activity')], max_length=1, verbose_name='活动类型')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('outline', models.TextField(blank=True, null=True, verbose_name='大纲')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField(blank=True, verbose_name='活动细节')),
                ('activity_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_creator', to='users.UserProfile', verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'activity',
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test project', max_length=100, verbose_name='项目名称')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('location', models.CharField(blank=True, default='some where', max_length=200, verbose_name='项目地点')),
                ('introduction', models.TextField(blank=True, verbose_name='项目简介')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='封面')),
                ('cost_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='花费预算')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='实际花费')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, verbose_name='定价')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='users.Organization', verbose_name='组织名称')),
                ('project_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creator', to='users.UserProfile', verbose_name='创建人')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='users.UserProfile', verbose_name='托管人')),
            ],
            options={
                'verbose_name': 'Project',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test material', max_length=100, verbose_name='材料名称')),
                ('introduction', models.TextField(blank=True, null=True, verbose_name='简介')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('resource', models.FileField(blank=True, null=True, upload_to='material/', verbose_name='资源地址')),
                ('activity', models.ManyToManyField(related_name='material', to='projects.Activity', verbose_name='活动')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.UserProfile', verbose_name='创建人')),
            ],
            options={
                'verbose_name': 'material',
                'db_table': 'material',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='projects.Project', verbose_name='项目'),
        ),
    ]
