# Generated by Django 2.2 on 2019-04-23 07:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20190423_0713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test project', max_length=100, verbose_name='')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('location', models.CharField(blank=True, default='some where', max_length=200)),
                ('introduction', models.TextField(blank=True)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('cost_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project', to='users.Organization')),
                ('project_creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_creator', to='users.UserProfile')),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_manager', to='users.UserProfile')),
            ],
            options={
                'verbose_name': 'Project',
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='test activity', max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('activity_type', models.CharField(choices=[('S', 'study'), ('O', 'online_study'), ('A', 'activity')], max_length=1)),
                ('cover', models.ImageField(blank=True, upload_to='')),
                ('details', django.contrib.postgres.fields.jsonb.JSONField()),
                ('activity_creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_creator', to='users.UserProfile')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='projects.Project')),
            ],
            options={
                'verbose_name': 'activity',
                'db_table': 'activity',
            },
        ),
    ]
