# Generated by Django 2.2 on 2019-04-17 09:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('ChineseName', models.CharField(default='', max_length=100)),
                ('EnglishName', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('Created_time', models.DateTimeField(auto_now_add=True)),
                ('LastSeen', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'ordering': ('Created_time',),
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
