# Generated by Django 2.2 on 2019-04-26 03:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='beijing', max_length=100, verbose_name='组织名称')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organization',
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(default='mouren', max_length=100, verbose_name='中文名')),
                ('english_name', models.CharField(blank=True, default='Unknown', max_length=100, verbose_name='英文名')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('last_seen', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company_id', models.IntegerField(verbose_name='员工号')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='职位')),
                ('email', models.EmailField(blank=True, max_length=100, verbose_name='电子邮件地址')),
                ('phone', models.PositiveIntegerField(blank=True, verbose_name='手机号')),
                ('department', models.CharField(blank=True, default='ISV', max_length=100, verbose_name='部门')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='users.Organization', verbose_name='组织名称')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_profile', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'user_profile',
                'ordering': ('created_time',),
            },
        ),
    ]
