# Generated by Django 2.2 on 2019-04-19 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='beijing', max_length=100)),
            ],
            options={
                'db_table': 'organizations',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chinese_name', models.CharField(default='mouren', max_length=100)),
                ('english_name', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('company_id', models.IntegerField()),
                ('position', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('phone', models.PositiveIntegerField(blank=True)),
                ('department', models.CharField(blank=True, default='ISV', max_length=100)),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.Organization')),
            ],
            options={
                'verbose_name': 'User Profile',
                'db_table': 'user',
                'ordering': ('created_time',),
            },
        ),
    ]
