# Generated by Django 2.2 on 2019-04-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='ID',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
