# Generated by Django 2.2 on 2019-04-29 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ('-created_time',), 'verbose_name': 'User Profile'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='组织名称'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='chinese_name',
            field=models.CharField(max_length=100, verbose_name='中文名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='company_id',
            field=models.IntegerField(unique=True, verbose_name='员工号'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='电子邮件地址'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='english_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='英文名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='手机号'),
        ),
    ]
