# Generated by Django 2.2 on 2019-04-17 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190417_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ID',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
