# Generated by Django 2.2 on 2019-04-19 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userprofile_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userprofile',
            table='user_profile',
        ),
    ]
